AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/rspec
    - bin/rubocop

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Metrics/LineLength:
  Max: 100
